### ISSUE TITLE
Updates to ringerModeStatus values

### ISSUE THREAD

**Issue by kirill09** [TryingOutSomething/sound_mode#10]
Thanks for the great library.
The first time the ringerModeStatus method is started, the value is correct, but if you disable silent mode on the device and re-request ringerModeStatus, the method will return an incorrect value

**Comment by TryingOutSomething** [comment]
Hi @kirill09, thanks for checking out the plugin and reporting the issue!

This issue seems similar to #9. I will check the issue out and get back to you :)

**Comment by TryingOutSomething** [comment]
Hi @kirill09, thank you so much for bringing up this issue. I did not consider the case where the user switches to another sound mode via the quick settings menu or the settings app. This issue made me realise that, and I appreciate it.

Pull request #9 submitted earlier has resolved this issue, and I have already merged and published the changes to pub.dev. Can you try the latest version and see if it resolves your issue?

I apologise for the issue that you faced while using the plugin.

**Comment by kirill09** [comment]
hi @TryingOutSomething The latest version does not have this problem. Thank you

**Comment by TryingOutSomething** [comment]
Thank you once again for trying out the plugin and reporting the issue! I'll be closing this thread :)
