### ISSUE TITLE
SoundModePlugin.java uses or overrides a deprecated API

### ISSUE THREAD

**Issue by Yasser85** [TryingOutSomething/sound_mode#13]
Hello
Thank you for the awesome package.
When I compile the project for android it shows this warning:
```
Note: C:\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\sound_mode-2.0.2\android\src\main\java\com\tryingoutsomething\soundmode\sound_mode\SoundModePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```
I know it's just a warning, and the app runs well.
But I think it needs to be replaced so it will work on the next versions of flutter.

Package version: sound_mode 2.0.2
Flutter SDK version: 3.0.2

**Comment by TryingOutSomething** [comment]
Hi @Yasser85 , thanks for checking the plugin.

I will check out the deprecation warning soon. Been busy with work and another personal project.

Thanks for bringing this warning to my attention! I appreciate it :)

**Comment by TryingOutSomething** [comment]
Hi @Yasser85 , I've addressed the deprecation warning errors in the most recent plugin version. 
I apologize for any delay, and thank you once more for exploring the plugin!
