### ISSUE TITLE
Weired return value for iOS device

### ISSUE THREAD

**Issue by Kotaro666-dev** [TryingOutSomething/sound_mode#3]
## Code I used

I used your code for example
https://github.com/TryingOutSomething/sound_mode/blob/master/example/lib/main.dart

## Weird retrun value

iOS device: iPhone SE(2nd gen)
Xcode: 12.1ver
Flutter: Channel stable, 1.20.3

I receive weired return values for ios device.

'Normal Moder1' for non-silent mode
'Vibrate Mode1'  for silent mode

Do you have any idea why this happens?

**Comment by TryingOutSomething** [comment]
Hi @Kotaro666-dev, thanks for trying out the plugin. I believe the example for iOS returns *Normal Moder* for non-silent mode and *Vibrate Mode* for silent mode when the ringerModeStatus from the SoundMode class. It can be seen [here](https://github.com/TryingOutSomething/sound_mode/blob/72304ca14a15c26a1df8ed0689c226786cd41ed4/ios/Classes/SwiftSoundModePlugin.swift#L17)

This is my fault for not checking the implementation for the iOS portion and making it consistent before merging into the project. I'll push an update tomorrow to make the return values more consistent with the Android side. 

Thanks for letting me know about this!

**Comment by TryingOutSomething** [comment]
@Kotaro666-dev I have pushed the update, let me know if the issue is resolved

**Comment by Kotaro666-dev** [comment]
@TryingOutSomething WOW, Thank you for your quick response and update! I will check it asap. Have a lovely day!

**Comment by Kotaro666-dev** [comment]
@TryingOutSomething I am  terribly sorry to be late for reporting back to you. Yes, the issue is resolved nicely!
I will close this issue now.

**Comment by TryingOutSomething** [comment]
@Kotaro666-dev no worries. Thanks for getting back :)
