### ISSUE TITLE
Phone volume is not reverted when put back to Normal Mode

### ISSUE THREAD

**Issue by samyadh** [TryingOutSomething/sound_mode#4]

**Comment by TryingOutSomething** [comment]
Hi, @samyadh. Thanks for trying out the plugin. Do you mind sharing if this issue occurs on iOS, Android or both?

**Comment by samyadh** [comment]
> Hi, @samyadh. Thanks for trying out the plugin. Do you mind sharing if this issue occurs on iOS, Android or both?

It's on Android. I am currently focusing on Android App for now. I use the OnePlus 7 Pro and Android Ver 10

**Comment by TryingOutSomething** [comment]
Got it. Let me take a look and get back to you on it. Thanks for the reply!

**Comment by TryingOutSomething** [comment]
> It's on Android. I am currently focusing on Android App for now. I use the OnePlus 7 Pro and Android Ver 10

Hi @samyadh, I apologize for the very late reply. I was busy with school.

I am not able to reproduce the error as I do not own an OnePlus device. I tried the app on an Android 10 but it seems to be working fine. 

Does the error still occur?

**Comment by TryingOutSomething** [comment]
Hi @samyadh, I'm closing this issue for now as I am not able to reproduce this error. Feel free to reopen this issue again if the issue persists.
