### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by yanivshaked** [TryingOutSomething/sound_mode#6]
I have submit a pull request for supporting null safety:
https://github.com/TryingOutSomething/sound_mode/pull/5

How soon can you integrate it?

**Comment by TryingOutSomething** [comment]
Hi @yanivshaked, thanks for taking the time to add on to the plugin! Let me test the plugin before I integrate it to the main branch and deploy the changes. I'll integrate it soon.

I'll inform you when the integration is done

**Comment by TryingOutSomething** [comment]
Hi @yanivshaked, I'm having some issues while trying to publish the changes because it's not reading the pubspec file when I run the publish command.

I've opened an issue on Flutter's repo page. I'll get back to you when the issue is resolved

**Comment by TryingOutSomething** [comment]
Hi @yanivshaked the plugin has been published successfully. I apologize for the false alarm. Do let me know if there are any issues with the plugin
