### ISSUE TITLE
_TypeError (type 'String' is not a subtype of type 'RingerModeStatus')

### ISSUE THREAD

**Issue by dmiedev** [TryingOutSomething/sound_mode#8]
Steps to reproduce:
1. Call `SoundMode.setSoundMode()`

Error occurs here:
```dart
        _currentRingerStatus =
            await _channel.invokeMethod(/* FUNCTION_NAME */);
```

`_channel.invokeMethod()` returns `String` while `_currentRingerStatus` is of `RingerModeStatus` type.

@JobMoll @TryingOutSomething Have you even tested the code?

**Comment by TryingOutSomething** [comment]
Hi @dmiedev , thanks for checking out the plugin!

I apologize for the issue you faced while trying out the plugin, it was working when I tried it out. It is my fault for not throughly checking the code before merging.

I will work on the fix right away and get back to you.

**Comment by job-46** [comment]
Hey, sorry for the inconvenience! I didn’t encounter this issue when I build the app. Should be an easy fix tho!

**Comment by TryingOutSomething** [comment]
@dmiedev I have pushed the fix to pub dev. Can you check if this fix resolves the issue?

**Comment by dmiedev** [comment]
> @dmiedev I have pushed the fix to pub dev. Can you check if this fix resolves the issue?

Hi! It seems to be working now! Thanks for the quick fix!

**Comment by TryingOutSomething** [comment]
No problem! Thanks for reporting the issue :)
